"""add_otp_and_transaction_tables

Revision ID: 4eaebd954afa
Revises: ec39623faf2a
Create Date: 2026-06-23 10:27:05.050880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eaebd954afa'
down_revision: Union[str, None] = 'ec39623faf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cheque_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_type', sa.Enum('APPROVE', 'REJECT', 'TIMEOUT', name='otp_response'), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cheque_id', sa.UUID(), nullable=False),
    sa.Column('drawer_account_id', sa.UUID(), nullable=False),
    sa.Column('payee_account_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('SETTLED', 'FAILED', name='transaction_status'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ),
    sa.ForeignKeyConstraint(['drawer_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payee_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('otp_events')
    # ### end Alembic commands ###