"""add_risk_scores_table

Revision ID: 768f13b1ac29
Revises: 42606c2215bd
Create Date: 2026-06-24 05:52:31.017975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768f13b1ac29'
down_revision: Union[str, None] = '42606c2215bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cheque_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('fraud_probability', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('anomaly_score', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('routing_decision', sa.String(length=20), nullable=False),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cheque_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    # ### end Alembic commands ###