"""add lstm_error to risk_scores

Revision ID: 8baedd88c5ff
Revises: addc26cfc846
Create Date: 2026-06-24 11:06:45.613547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baedd88c5ff'
down_revision: Union[str, None] = 'addc26cfc846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('lstm_error', sa.DECIMAL(precision=6, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'lstm_error')
    # ### end Alembic commands ###