"""add_cheque_models

Revision ID: ec39623faf2a
Revises: 207a6cb2bab8
Create Date: 2026-06-18 16:38:02.958340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec39623faf2a'
down_revision: Union[str, None] = '207a6cb2bab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheque_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('book_sequence', sa.Integer(), nullable=False),
    sa.Column('total_leaves', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheque_leaves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leaf_serial', sa.String(length=30), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('leaf_sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'ACTIVE', 'USED', 'CANCELLED', 'EXPIRED', name='leaf_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['cheque_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheque_leaves_leaf_serial'), 'cheque_leaves', ['leaf_serial'], unique=True)
    op.create_table('cheques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leaf_id', sa.UUID(), nullable=False),
    sa.Column('leaf_serial', sa.String(length=30), nullable=False),
    sa.Column('drawer_account_id', sa.UUID(), nullable=False),
    sa.Column('payee_account_number', sa.String(length=18), nullable=False),
    sa.Column('payee_name', sa.String(length=100), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('cheque_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_a_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qr_b_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qr_c_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'PENDING_COSIGN', 'PRESENTED', 'OTP_PENDING', 'OTP_APPROVED', 'CLEARED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='cheque_status'), nullable=False),
    sa.Column('multi_sig_required', sa.Boolean(), nullable=False),
    sa.Column('cosigner_account_id', sa.UUID(), nullable=True),
    sa.Column('issue_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('png_s3_key', sa.String(), nullable=True),
    sa.Column('pdf_s3_key', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cosigner_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['drawer_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['leaf_id'], ['cheque_leaves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leaf_id')
    )
    op.create_index(op.f('ix_cheques_cheque_hash'), 'cheques', ['cheque_hash'], unique=True)
    op.create_index(op.f('ix_cheques_leaf_serial'), 'cheques', ['leaf_serial'], unique=False)
    op.create_table('cheque_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cheque_id', sa.UUID(), nullable=False),
    sa.Column('signer_account_id', sa.UUID(), nullable=False),
    sa.Column('signature_hex', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('webauthn_used', sa.Boolean(), nullable=False),
    sa.Column('biometric_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cheque_id'], ['cheques.id'], ),
    sa.ForeignKeyConstraint(['signer_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheque_signatures')
    op.drop_index(op.f('ix_cheques_leaf_serial'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_cheque_hash'), table_name='cheques')
    op.drop_table('cheques')
    op.drop_index(op.f('ix_cheque_leaves_leaf_serial'), table_name='cheque_leaves')
    op.drop_table('cheque_leaves')
    op.drop_table('cheque_books')
    # ### end Alembic commands ###